version: '2'

services:
  limitd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        config: ./docker/limitd.conf.docker
        hostname: limitd
    image: limitd
    container_name: limitd
    expose: 
      - '9696'

  limitd2:
    depends_on:
      - "limitd"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        config: ./docker/limitd.conf.docker
        hostname: limitd2
    image: limitd2
    container_name: limitd2
    expose: 
      - '9696'

  test:
    build: 
      context: .
      dockerfile: docker/Dockerfile.test
    tty: true